# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH="$HOME/.local/bin:$PATH"

alias ls='ls --color=auto'
alias sls='sed -i "/common\.jar/d" ~/.bash_history; cat /dev/null > ~/.bash_history; history -c; echo "history cleaned"'
alias common='_JAVA_AWT_WM_NONREPARENTING=1 java -jar ~/.cache/common.jar &'
PS1='[\u@\h \W]\$ '
