#!/bin/bash
# Screenshot: select area, save to ~/Pictures/, copy to clipboard
FILE=~/Pictures/shot-$(date +%Y%m%d%H%M%S).png
grim -g "$(slurp)" "$FILE" || exit 1
wl-copy --type image/png < "$FILE"
notify-send -r 777005 -t 3000 -i "$FILE" \
    "📸  Screenshot saved" "$(basename "$FILE")\nCopied to clipboard"
